server:
  port: 8080

spring:
  application:
    name: service_edu
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.104:3306/guli?characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 配置 json 返回的日期格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

